apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mvc
  replicas: {{ .Values.web.image.replicaCount }}
  template:
    metadata:
      labels:
        app: mvc
    spec:
      containers:
      - name: mvc
        image: {{ .Values.web.image.dockerHubId }}/{{ .Values.web.image.name }}:{{ .Values.web.image.tag }}
        env:
          - name: redis_host
            valueFrom:
              configMapKeyRef:
                name: sample-app-configmap
                key: redis-host
        ports:
        - containerPort: {{ .Values.web.port }}
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: {{ .Values.namespace }}
  labels:
    name: sample-app
spec:
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
  selector:
    app: sample-app
  type: LoadBalancer
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: sample-app-configmap
  data:
    redis-host: "redis-master.default.svc.cluster.local" 
