apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
        app: sample-app
        id: "0"
  template:
    metadata:
      labels:
        app: sample-app
        id: "0"
    spec:
      containers:
      - name: sample-app
        image: chikucute99/sample-app:latest
        env:
          - name: redis_host
            valueFrom:
              configMapKeyRef:
                name: sample-app-configmap
                key: redis-host                             
        ports:
        - containerPort: 1982
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: {{ .Values.namespace }}
  labels:
    name: sample-app
spec:
  ports:
    - port: 1982
      targetPort: 1982
      protocol: TCP
  selector:
    app: sample-app
  type: LoadBalancer
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: sample-app-configmap
	namespace: {{ .Values.namespace }}
  data:
    redis-host: "redis-master.default.svc.cluster.local"  
